version: "3.8"
services:
  backend:
    build:
      context: ./back
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./front
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
