# Usa una imagen base para servir contenido estático
FROM nginx:alpine

# Copia todo el contenido del directorio `front` al directorio raíz de Nginx
COPY . /usr/share/nginx/html/

# Expone el puerto 80 para el servidor web
EXPOSE 80
